# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Textbox(object):
    def setupUi(self, Textbox):
        Textbox.setObjectName("Textbox")
        Textbox.resize(1091, 476)
        Textbox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Textbox.setMouseTracking(True)
        Textbox.setStyleSheet("QTextEdit { \n"
"qproperty-frame: false\n"
"}")
        self.Box = QtWidgets.QFrame(Textbox)
        self.Box.setGeometry(QtCore.QRect(380, 220, 241, 61))
        self.Box.setMinimumSize(QtCore.QSize(221, 61))
        self.Box.setMouseTracking(True)
        self.Box.setTabletTracking(True)
        self.Box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Box.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Box.setLineWidth(3)
        self.Box.setMidLineWidth(3)
        self.Box.setObjectName("Box")
        self.BottomFrame = QtWidgets.QFrame(self.Box)
        self.BottomFrame.setGeometry(QtCore.QRect(0, 20, 241, 41))
        self.BottomFrame.setMinimumSize(QtCore.QSize(221, 41))
        self.BottomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BottomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomFrame.setObjectName("BottomFrame")
        self.textEditor = QtWidgets.QTextEdit(self.BottomFrame)
        self.textEditor.setGeometry(QtCore.QRect(0, 0, 241, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditor.sizePolicy().hasHeightForWidth())
        self.textEditor.setSizePolicy(sizePolicy)
        self.textEditor.setMinimumSize(QtCore.QSize(221, 41))
        self.textEditor.setStyleSheet("QTextEdit { qproperty-frame: false}")
        self.textEditor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditor.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditor.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEditor.setLineWrapColumnOrWidth(8)
        self.textEditor.setOverwriteMode(True)
        self.textEditor.setObjectName("textEditor")
        self.TopFrame = QtWidgets.QFrame(self.Box)
        self.TopFrame.setGeometry(QtCore.QRect(0, 0, 239, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.TopFrame.sizePolicy().hasHeightForWidth())
        self.TopFrame.setSizePolicy(sizePolicy)
        self.TopFrame.setMinimumSize(QtCore.QSize(221, 21))
        self.TopFrame.setMaximumSize(QtCore.QSize(16777215, 21))
        self.TopFrame.setMouseTracking(True)
        self.TopFrame.setAcceptDrops(True)
        self.TopFrame.setAutoFillBackground(False)
        self.TopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopFrame.setObjectName("TopFrame")
        self.DragWidget = QtWidgets.QWidget(self.TopFrame)
        self.DragWidget.setGeometry(QtCore.QRect(0, 0, 161, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DragWidget.sizePolicy().hasHeightForWidth())
        self.DragWidget.setSizePolicy(sizePolicy)
        self.DragWidget.setMinimumSize(QtCore.QSize(161, 21))
        self.DragWidget.setMaximumSize(QtCore.QSize(16777215, 21))
        self.DragWidget.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.DragWidget.setMouseTracking(True)
        self.DragWidget.setObjectName("DragWidget")
        self.MeatballIcon = QtWidgets.QLabel(self.DragWidget)
        self.MeatballIcon.setGeometry(QtCore.QRect(120, 0, 16, 16))
        self.MeatballIcon.setMaximumSize(QtCore.QSize(16, 16))
        self.MeatballIcon.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.MeatballIcon.setMouseTracking(True)
        self.MeatballIcon.setAcceptDrops(True)
        self.MeatballIcon.setText("")
        self.MeatballIcon.setPixmap(QtGui.QPixmap(":/png/icons8-menu-16.png"))
        self.MeatballIcon.setObjectName("MeatballIcon")
        self.SpacerFrame = QtWidgets.QGroupBox(self.TopFrame)
        self.SpacerFrame.setGeometry(QtCore.QRect(160, 0, 21, 21))
        self.SpacerFrame.setStyleSheet("QGroupBox: {\n"
"border:0\n"
"}")
        self.SpacerFrame.setFlat(True)
        self.SpacerFrame.setObjectName("SpacerFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.SpacerFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.WidthChanger = QtWidgets.QWidget(self.TopFrame)
        self.WidthChanger.setGeometry(QtCore.QRect(180, 0, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WidthChanger.sizePolicy().hasHeightForWidth())
        self.WidthChanger.setSizePolicy(sizePolicy)
        self.WidthChanger.setMinimumSize(QtCore.QSize(61, 21))
        self.WidthChanger.setMaximumSize(QtCore.QSize(16777215, 21))
        self.WidthChanger.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.WidthChanger.setMouseTracking(True)
        self.WidthChanger.setAcceptDrops(True)
        self.WidthChanger.setObjectName("WidthChanger")
        self.HorizontalArrowsIcon = QtWidgets.QLabel(self.WidthChanger)
        self.HorizontalArrowsIcon.setGeometry(QtCore.QRect(40, 0, 16, 16))
        self.HorizontalArrowsIcon.setMaximumSize(QtCore.QSize(16, 16))
        self.HorizontalArrowsIcon.setMouseTracking(True)
        self.HorizontalArrowsIcon.setText("")
        self.HorizontalArrowsIcon.setPixmap(QtGui.QPixmap(":/png/icons8-resize-horizontal-16.png"))
        self.HorizontalArrowsIcon.setObjectName("HorizontalArrowsIcon")

        self.retranslateUi(Textbox)
        QtCore.QMetaObject.connectSlotsByName(Textbox)

    def retranslateUi(self, Textbox):
        _translate = QtCore.QCoreApplication.translate
        Textbox.setWindowTitle(_translate("Textbox", "Form"))
        self.textEditor.setHtml(_translate("Textbox", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
import resources.ResourceFile_rc
